config/routes.rb
Rails.application.routes.draw do


    devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

    devise_for :admin, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    resources :shops do
      collection do
        get :search
      end
      resources :reviews
      resources :items
      resources :news
      resources :services
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers do
      collection do
        get :like
        get :top
        get :confirm
      end
      resources :reviews, only: [:index]
    end
    patch '/withdrawal' => 'customers#withdrawal'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :shops do
      collection do
        get :top
      end
      resources :news
      resources :items
      resources :services
      resources :top_banners
      resources :reviews
      resource :favorites
    end
    resources :admins do
      get :confirm
    end
    patch '/withdrawal' => 'admins#withdrawal'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :top_banners, dependent: :destroy

  has_one :shop, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active === "vaild")
  end

  enum is_active: { vaild: true, invaild: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

    enum state: {
     "都道府県":0,
     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
     沖縄県: 47
  }

  def active_for_authentication?
    super && (self.is_active === "vaild")
  end


  enum is_active: { vaild: true, invaild: false }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :shop
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :name, presence: true
  validates :content, presence: true
  validates :price, presence: true

  def tax_price
    (self.price * 1.10).round
  end
end

app/models/news.rb
class News < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :title, presence: true
  validates :content, presence: true

  enum genre: { info: 0, blog: 1, event: 2 }
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :shop
  belongs_to :customer

  validates :title, presence: true
  validates :content, presence: true
end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :shop

  validates :title, presence: true
  validates :content, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord

  has_many :top_banners, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :admin

  attachment :image
  attachment :logo

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :business_hours, presence: true
  validates :holiday, presence: true

  enum shop_genre: { gourmet: 0, shopping: 1, relaxation: 2, beauty_salon: 3, school: 4, private_school: 5,
                     dental: 6, hospital: 7, outdoor: 8, second_shop: 9, pet: 10,
                     life_support: 11, lear_estate: 12, ceremonial: 13

  }

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/models/top_banner.rb
class TopBanner < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :image, presence: true
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    @news.shop_id = current_admin.shop.id
    if @news.save
      redirect_to admin_shop_news_index_path
    else
      render :new
    end
  end

  def index
    @current_news = current_admin.shop.news.order(created_at: :desc)
    @shop = current_admin.shop.id
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to admin_shop_news_path(@news)
    else
      render :edit
    end
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    redirect_to admin_shop_news_index_path
  end

  private

  def news_params
    params.require(:news).permit(:shop_id, :genre, :title, :image, :content)
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.shop_id = current_admin.shop.id
    if @service.save
      redirect_to admin_shop_services_path
    else
      render :new
    end
  end

  def index
    @services = current_admin.shop.services
    @shop = current_admin.shop.id
  end

  def show
    @service = Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to admin_shop_services_path
    else
      render :edit
    end
  end

  def destroy
    service = Service.find(params[:id])
    service.destroy
    redirect_to admin_shop_services_path
  end

  private

  def service_params
    params.require(:service).permit(:shop_id, :title, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path # ログアウト後に遷移するpathを設定
    else
      new_admin_session_path
    end
  end

  def set_search
    @q = Shop.ransack(params[:q])
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :state, :city, :is_active, :phone, :company_name])
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/top_banners_helper.rb
module Admin::TopBannersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/services/create.html.erb
<h1>Admin::Services#create</h1>
<p>Find me in app/views/admin/services/create.html.erb</p>

app/views/admin/services/destroy.html.erb
<h1>Admin::Services#destroy</h1>
<p>Find me in app/views/admin/services/destroy.html.erb</p>

app/views/admin/services/edit.html.erb
<main>
  <div class="head">
    <h1>サービス編集フォーム</h1>
  </div>
  <div class="validate">
  <% if @service.errors.any? %>
    <h3><%= @service.errors.count %>件のエラーが発生しました</h3>
    <% @service.errors.full_messages.each do |message| %>
      <p class="validate-text"><%= message %></p>
    <% end %>
  <% end %>
  </div>
  <%= form_with model: @service, url: {controller: 'services', action: 'update' }, local:true do |f| %>
  <div class="form">
    <div class="form_group">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
    </div>
    <div class="form_group">
      <%= f.label :content, "内容説明" %>
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit "保存する" %>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/services/index.html.erb
<main>
  <div class="head">
    <h1>サービス一覧</h1>
  </div>
  <div class="layer">
    <%= link_to top_admin_shops_path do %>
    <i class="fas fa-chevron-left">&thinsp;店舗トップページに戻る</i>
    <% end %>
  </div>
  <div class="content-list service">
      <div class="new-action">
        <%= link_to new_admin_shop_service_path do %>
        <i class="fas fa-plus">&thinsp;新規作成</i>
        <% end %>
      </div>
      <ul>
        <% @services.each do |service| %>
        <li>
          <h2><%= service.title %></h2>
          <p><%= service.content %></p>
          <div class="edit-action">
            <p>
              <%= link_to edit_admin_shop_service_path(@shop, service) do %>
              <i class="far fa-edit">&thinsp;編集する</i>
              <% end %>
            </p>
            <p>
              <%= link_to admin_shop_service_path(@shop, service), method: :delete do %>
              <i class="far fa-trash-alt">&thinsp;削除する</i>
              <% end %>
            </p>
          </div>
        </li>
        <% end %>
      </ul>
  </div>
</main>

app/views/admin/services/new.html.erb
<main>
  <div class="head">
    <h1>サービス作成フォーム</h1>
  </div>
  <div class="validate">
  <% if @service.errors.any? %>
    <h3><%= @service.errors.count %>件のエラーが発生しました</h3>
    <% @service.errors.full_messages.each do |message| %>
      <p class="validate-text"><%= message %></p>
    <% end %>
  <% end %>
  </div>
  <%= form_with model: @service, url: {controller: 'services', action: 'create' }, local:true do |f| %>
  <div class="form">
    <div class="form_group">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
    </div>
    <div class="form_group">
      <%= f.label :content, "内容説明" %>
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit "登録する" %>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/services/show.html.erb
<h1>Admin::Services#show</h1>
<p>Find me in app/views/admin/services/show.html.erb</p>

app/views/admin/services/update.html.erb
<h1>Admin::Services#update</h1>
<p>Find me in app/views/admin/services/update.html.erb</p>