config/routes.rb
Rails.application.routes.draw do


    devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

    devise_for :admin, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    resources :shops do
      collection do
        get :search
      end
      resources :reviews
      resources :items
      resources :news
      resources :services
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers do
      collection do
        get :like
        get :top
        get :confirm
      end
      resources :reviews, only: [:index]
    end
    patch '/withdrawal' => 'customers#withdrawal'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :shops do
      collection do
        get :top
      end
      resources :news
      resources :items
      resources :services
      resources :top_banners
      resources :reviews
      resource :favorites
    end
    resources :admins do
      get :confirm
    end
    patch '/withdrawal' => 'admins#withdrawal'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :top_banners, dependent: :destroy

  has_one :shop, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active === "vaild")
  end

  enum is_active: { vaild: true, invaild: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

    enum state: {
     "都道府県":0,
     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
     沖縄県: 47
  }

  def active_for_authentication?
    super && (self.is_active === "vaild")
  end


  enum is_active: { vaild: true, invaild: false }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :shop
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :name, presence: true
  validates :content, presence: true
  validates :price, presence: true

  def tax_price
    (self.price * 1.10).round
  end
end

app/models/news.rb
class News < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :title, presence: true
  validates :content, presence: true

  enum genre: { info: 0, blog: 1, event: 2 }
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :shop
  belongs_to :customer

  validates :title, presence: true
  validates :content, presence: true
end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :shop

  validates :title, presence: true
  validates :content, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord

  has_many :top_banners, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :admin

  attachment :image
  attachment :logo

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :business_hours, presence: true
  validates :holiday, presence: true

  enum shop_genre: { gourmet: 0, shopping: 1, relaxation: 2, beauty_salon: 3, school: 4, private_school: 5,
                     dental: 6, hospital: 7, outdoor: 8, second_shop: 9, pet: 10,
                     life_support: 11, lear_estate: 12, ceremonial: 13

  }

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/models/top_banner.rb
class TopBanner < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :image, presence: true
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    @news.shop_id = current_admin.shop.id
    if @news.save
      redirect_to admin_shop_news_index_path
    else
      render :new
    end
  end

  def index
    @current_news = current_admin.shop.news.order(created_at: :desc)
    @shop = current_admin.shop.id
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to admin_shop_news_path(@news)
    else
      render :edit
    end
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    redirect_to admin_shop_news_index_path
  end

  private

  def news_params
    params.require(:news).permit(:shop_id, :genre, :title, :image, :content)
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.admin_id = current_admin.id
    if @shop.save
      redirect_to admin_shop_path(@shop)
    else
      render :new
    end
  end

  def top
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to admin_shop_path(@shop)
    else
      render :edit
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:admin_id, :name, :shop_genre, :postal_code, :state, :city, :address, :phone, :access, :parking, :business_hours, :holiday, :credit_card, :cash_less, :homepage, :image,  :logo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path # ログアウト後に遷移するpathを設定
    else
      new_admin_session_path
    end
  end

  def set_search
    @q = Shop.ransack(params[:q])
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :state, :city, :is_active, :phone, :company_name])
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/top_banners_helper.rb
module Admin::TopBannersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shops/create.html.erb
<h1>Admin::Shops#create</h1>
<p>Find me in app/views/admin/shops/create.html.erb</p>

app/views/admin/shops/edit.html.erb
<main>
  <div class="head">
    <h1>店舗情報編集フォーム</h1>
  </div>
  <div class="layer">
    <%= link_to top_admin_shops_path do %>
    <i class="fas fa-chevron-left">&thinsp;店舗トップページに戻る</i>
    <% end %>
  </div>
  <div class="validate">
  <% if @shop.errors.any? %>
    <h3><%= @shop.errors.count %>件のエラーが発生しました</h3>
    <% @shop.errors.full_messages.each do |message| %>
      <p class="validate-text"><%= message %></p>
    <% end %>
  <% end %>
  </div>
  <%= form_with model: @shop, url: {controller: 'shops', action: 'update' }, local:true do |f| %>
  <div class="form">
    <div class="form_group">
      <%= f.label :name, "会社名または店舗名" %>
      <%= f.text_field :name %>
    </div>
    <div class="form_group">
      <%= f.label :shop_genre, "お店のジャンル" %>
      <%= f.select :shop_genre, Shop.shop_genres_i18n.invert, {} %>
    </div>
    <div class="form_group">
      <%= f.label :postal_code, "郵便番号(ハイフンなし）" %>
      <%= f.text_field :postal_code %>
    </div>
    <div class="form_group">
      <%= f.label :address, "住所" %>
      <%= f.text_field :address %>
    </div>
    <div class="form_group">
      <%= f.label :phone, "電話番号（ハイフンなし）" %>
      <%= f.text_field :phone %>
    </div>
    <div class="form_group">
      <%= f.label :access, "アクセス" %>
      <%= f.text_field :access %>
    </div>
    <div class="form_group">
      <%= f.label :parking, "駐車場の有無" %>
      <%= f.text_field :parking %>
    </div>
    <div class="form_group">
      <%= f.label :business_hours, "営業時間" %>
      <%= f.text_field :business_hours %>
    </div>
    <div class="form_group">
      <%= f.label :holiday, "定休日" %>
      <%= f.text_field :holiday %>
    </div>
    <div class="form_group">
      <%= f.label :homepage, "ホームページURL" %>
      <%= f.text_field :homepage %>
    </div>
    <div class="form_group">
      <%= f.label :image, "メイン画像" %>
      <%= f.attachment_field :image, class: 'logo-form' %>
    </div>
    <div class="form_group">
      <%= f.label :logo, "ロゴマーク" %>
      <%= f.attachment_field :logo, class: 'logo-form' %>
    </div>
    <div class="actions">
      <%= f.submit "保存する" %>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/shops/new.html.erb
<main>
  <div class="head">
    <h1>店舗情報作成フォーム</h1>
  </div>
  <div class="validate">
  <% if @shop.errors.any? %>
    <h3><%= @shop.errors.count %>件のエラーが発生しました</h3>
    <% @shop.errors.full_messages.each do |message| %>
      <p class="validate-text"><%= message %></p>
    <% end %>
  <% end %>
  </div>
  <%= form_with model: @shop, url: admin_shops_path, local:true do |f| %>
  <div class="form">
    <div class="form_group">
      <%= f.label :name, "会社名または店舗名" %>
      <%= f.text_field :name %>
    </div>
    <div class="form_group">
      <%= f.label :shop_genre, "お店のジャンル" %>
      <%= f.select :shop_genre, Shop.shop_genres_i18n.invert, {} %>
    </div>
    <div class="form_group">
      <%= f.label :postal_code, "郵便番号(ハイフンなし）" %>
      <%= f.text_field :postal_code %>
    </div>
    <div class="form_group">
      <%= f.label :address, "住所" %>
      <%= f.text_field :address %>
    </div>
    <div class="form_group">
      <%= f.label :phone, "電話番号（ハイフンなし）" %>
      <%= f.text_field :phone %>
    </div>
    <div class="form_group">
      <%= f.label :access, "アクセス" %>
      <%= f.text_field :access %>
    </div>
    <div class="form_group">
      <%= f.label :parking, "駐車場の有無" %>
      <%= f.text_field :parking %>
    </div>
    <div class="form_group">
      <%= f.label :business_hours, "営業時間" %>
      <%= f.text_field :business_hours %>
    </div>
    <div class="form_group">
      <%= f.label :holiday, "定休日" %>
      <%= f.text_field :holiday %>
    </div>
    <div class="form_group">
      <%= f.label :homepage, "ホームページURL" %>
      <%= f.text_field :homepage %>
    </div>
    <div class="form_group">
      <%= f.label :image, "メイン画像" %>
      <%= f.attachment_field :image, class: 'logo-form' %>
    </div>
    <div class="form_group">
      <%= f.label :logo, "ロゴマーク" %>
      <%= f.attachment_field :logo, class: 'logo-form' %>
    </div>
    <div class="actions">
      <%= f.submit "登録する" %>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/shops/show.html.erb
<main>
  <div class="head">
    <h1>店舗情報詳細</h1>
  </div>
  <div class="layer">
    <%= link_to top_admin_shops_path do %>
    <i class="fas fa-chevron-left">&thinsp;店舗トップページに戻る</i>
    <% end %>
  </div>
  <div class="shop-detail">
    <div class="shop-edit-action">
      <%= link_to edit_admin_shop_path(@shop) do %>
      <i class="far fa-edit">&thinsp;編集する</i>
      <% end %>
    </div>
    <ul>
      <li>
        <dl>
          <dt>会社名または店舗名</dt>
          <dd><%= current_admin.shop.name %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>お店のジャンル</dt>
          <dd><%= current_admin.shop.shop_genre_i18n %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>郵便番号</dt>
          <dd><%= current_admin.shop.postal_code %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>住所</dt>
          <dd><%= current_admin.shop.address %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>電話番号</dt>
          <dd><%= current_admin.shop.phone %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>アクセス</dt>
          <dd>
            <% if current_admin.shop.access.blank? %>
            未設定
            <% else %>
            <%= current_admin.shop.access %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>駐車場の有無</dt>
          <dd>
            <% if current_admin.shop.parking.blank? %>
            未設定
            <% else %>
            <%= current_admin.shop.parking %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>営業時間</dt>
          <dd>
            <% if current_admin.shop.business_hours.blank? %>
            未設定
            <% else %>
            <%= current_admin.shop.business_hours %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>定休日</dt>
          <dd>
            <% if current_admin.shop.holiday.blank? %>
            未設定
            <% else %>
            <%= current_admin.shop.holiday %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>ホームページURL</dt>
          <dd>
            <% if current_admin.shop.homepage.blank? %>
            未設定
            <% else %>
            <%= current_admin.shop.homepage %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>メイン画像</dt>
          <dd>
            <% if current_admin.shop.image_id.blank? %>
            未設定
            <% else %>
            <%= attachment_image_tag current_admin.shop, :image %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>ロゴマーク</dt>
          <dd>
            <% if current_admin.shop.logo_id.blank? %>
            未設定
            <% else %>
            <%= attachment_image_tag current_admin.shop, :logo %>
            <% end %>
          </dd>
        </dl>
      </li>
    </ul>
  </div>
</main>

app/views/admin/shops/top.html.erb
<main>
  <div class="head">
    <h1>店舗作成フォーム</h1>
  </div>
  <div class="shop-create">
    <% if current_admin.shop.nil? %>
    <p>※店舗情報の作成後、全てのフォームを作成いただけます。</p>
    <ul>
      <li>
        <%= link_to new_admin_shop_path do %>
        <div class="shop-create_content">
          <%= image_tag('shop-info-icon.png') %>
          <h2>店舗情報</h2>
          <p>まちわっかに出店する店舗情報の登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <li>
        <div class="shop-create_content">
          <%= image_tag('bannar-icon.png') %>
          <h2>トップバナー</h2>
          <p>店舗詳細ページのバナーの登録・編集ができます。</p>
        </div>
      </li>
      <li>
        <div class="shop-create_content">
          <%= image_tag('service-icon.png') %>
          <h2>サービス</h2>
          <p>お客様に提供しているサービスの登録・編集ができます。</p>
        </div>
      </li>
      <li>
        <div class="shop-create_content">
          <%= image_tag('menu-icon.png') %>
          <h2>商品/メニュー</h2>
          <p>お客様に提供する、商品またはメニューの登録・編集ができます。</p>
        </div>
      </li>
      <li>
        <div class="shop-create_content">
          <%= image_tag('news-icon.png') %>
          <h2>ニュース</h2>
          <p>店舗のお知らせ・ブログ・イベントの登録・編集ができます。</p>
        </div>
      </li>
    </ul>
    <% else %>
    <ul>
      <li>
        <%= link_to admin_shop_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('shop-info-icon.png') %>
          <h2>店舗情報</h2>
          <p>まちわっかに出店する店舗情報の登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% if current_admin.shop.top_banners.empty? %>
      <li>
        <%= link_to new_admin_shop_top_banner_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('bannar-icon.png') %>
          <h2>トップバナー</h2>
          <p>店舗詳細ページのバナーの登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to admin_shop_top_banners_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('bannar-icon.png') %>
          <h2>トップバナー</h2>
          <p>店舗詳細ページのバナーの登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% end %>
      <% if current_admin.shop.services.empty? %>
      <li>
        <%= link_to new_admin_shop_service_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('service-icon.png') %>
          <h2>サービス</h2>
          <p>お客様に提供しているサービスの登録・編集ができます。<</p>
        </div>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to admin_shop_services_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('service-icon.png') %>
          <h2>サービス</h2>
          <p>お客様に提供しているサービスの登録・編集ができます。<</p>
        </div>
        <% end %>
      </li>
      <% end %>
      <% if current_admin.shop.items.empty? %>
      <li>
        <%= link_to new_admin_shop_item_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('menu-icon.png') %>
          <h2>商品/メニュー</h2>
          <p>お客様に提供する、商品またはメニューの登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to admin_shop_items_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('menu-icon.png') %>
          <h2>商品/メニュー</h2>
          <p>お客様に提供する、商品またはメニューの登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% end %>
      <% if current_admin.shop.news.empty? %>
      <li>
        <%= link_to new_admin_shop_news_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('news-icon.png') %>
          <h2>ニュース</h2>
          <p>店舗のお知らせ・ブログ・イベントの登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to admin_shop_news_index_path(current_admin.shop.id) do %>
        <div class="shop-create_content">
          <%= image_tag('news-icon.png') %>
          <h2>ニュース</h2>
          <p>店舗のお知らせ・ブログ・イベントの登録・編集ができます。</p>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
    <% end %>
  </div>
</main>

app/views/admin/shops/update.html.erb
<h1>Admin::Shops#update</h1>
<p>Find me in app/views/admin/shops/update.html.erb</p>