config/routes.rb
Rails.application.routes.draw do


    devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

    devise_for :admin, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  scope module: :public do
    root to: "homes#top"
    resources :shops do
      collection do
        get :search
      end
      resources :reviews
      resources :items
      resources :news
      resources :services
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers do
      collection do
        get :like
        get :top
        get :confirm
      end
      resources :reviews, only: [:index]
    end
    patch '/withdrawal' => 'customers#withdrawal'
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :shops do
      collection do
        get :top
      end
      resources :news
      resources :items
      resources :services
      resources :top_banners
      resources :reviews
      resource :favorites
    end
    resources :admins do
      get :confirm
    end
    patch '/withdrawal' => 'admins#withdrawal'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :top_banners, dependent: :destroy

  has_one :shop, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active === "vaild")
  end

  enum is_active: { vaild: true, invaild: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

    enum state: {
     "都道府県":0,
     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
     沖縄県: 47
  }

  def active_for_authentication?
    super && (self.is_active === "vaild")
  end


  enum is_active: { vaild: true, invaild: false }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :shop
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :name, presence: true
  validates :content, presence: true
  validates :price, presence: true

  def tax_price
    (self.price * 1.10).round
  end
end

app/models/news.rb
class News < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :title, presence: true
  validates :content, presence: true

  enum genre: { info: 0, blog: 1, event: 2 }
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :shop
  belongs_to :customer

  validates :title, presence: true
  validates :content, presence: true
end

app/models/service.rb
class Service < ApplicationRecord

  belongs_to :shop

  validates :title, presence: true
  validates :content, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord

  has_many :top_banners, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  belongs_to :admin

  attachment :image
  attachment :logo

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :business_hours, presence: true
  validates :holiday, presence: true

  enum shop_genre: { gourmet: 0, shopping: 1, relaxation: 2, beauty_salon: 3, school: 4, private_school: 5,
                     dental: 6, hospital: 7, outdoor: 8, second_shop: 9, pet: 10,
                     life_support: 11, lear_estate: 12, ceremonial: 13

  }

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/models/top_banner.rb
class TopBanner < ApplicationRecord

  belongs_to :shop

  attachment :image

  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path # ログアウト後に遷移するpathを設定
    else
      new_admin_session_path
    end
  end

  def set_search
    @q = Shop.ransack(params[:q])
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :state, :city, :is_active, :phone, :company_name])
  end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/confirm.html.erb
<main>
  <div class="withdrawal">
    <p><i class="fas fa-exclamation-circle"></i>退会手続きの前にご確認ください</p>
    <div class="withdrawal_text">
      <p>出店者会員を退会された場合には、現在登録されているお店の情報やブックマーク・レビューの履歴を公開することができなくなります。退会をする場合は「退会する」をクリックしてください。</p>
    </div>
    <%= form_with(url:admin_withdrawal_path, local:true, method: :patch) do |f| %>
    <div class="decision">
      <%= link_to "退会しない", admin_path(current_customer) %>
      <%= f.submit "退会する", data: { confirm: "本当に退会しますか？"}, class: 'button' %>
    </div>
    <% end %>
  </div>
</main>

app/views/admin/admins/edit.html.erb
<main>
  <div class="head">
    <h1>登録情報編集フォーム</h1>
  </div>
  <div class="layer">
    <%= link_to admin_path do %>
    <i class="fas fa-chevron-left">&thinsp;マイページに戻る</i>
    <% end %>
  </div>
  <%= form_with model: @admin, url: {controller: 'admins', action: 'update' }, local:true do |f| %>
  <div class="form">

  <div class="form_group">
    <%= f.label :company_name, "会社名" %><br />
    <%= f.text_field :company_name, autofocus: true, autocomplete: "company_name" %>
  </div>

  <div class="form_group">
    <%= f.label :name, "お名前" %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="form_group">
    <%= f.label :name_kana, "フリガナ" %><br />
    <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana" %>
  </div>

  <div class="form_group">
    <%= f.label :email, "メールアドレス" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

    <div class="form_group">
    <%= f.label :phone, "電話番号" %><br />
    <%= f.text_field :phone, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する" %>
  </div>
  <% end %>
  </div>
  <div class="withdrawal-action">
    <%= link_to "退会する", admin_admin_confirm_path(@admin) %>
  </div>
</main>

app/views/admin/admins/show.html.erb
<main>
  <div class="head">
    <h1>登録情報</h1>
  </div>
  <div class="layer">
    <%= link_to admin_path do %>
    <i class="fas fa-chevron-left">&thinsp;マイページに戻る</i>
    <% end %>
  </div>
    <ul class="admin-content">
      <li>
        <dl>
          <dt>会社名</dt>
          <dd><%= @admin.company_name %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>お名前</dt>
          <dd>
            <% if @admin.name.blank? %>
            未登録
            <% else %>
            <%= @admin.name %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>フリガナ</dt>
          <dd>
            <% if @admin.name_kana.blank? %>
            未登録
            <% else %>
            <%= @admin.name_kana %>
            <% end %>
          </dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>メールアドレス</dt>
          <dd><%= @admin.email %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>電話番号</dt>
          <dd>
            <% if @admin.phone.blank? %>
            未登録
            <% else %>
            <%= @admin.phone %>
            <% end %>
          </dd>
        </dl>
      </li>
    </ul>
    <div class="user-edit-action">
      <%= link_to edit_admin_admin_path(@admin) do %>
      <i class="far fa-edit">&thinsp;編集する</i>
      <% end %>
    </div>
</main>

app/views/admin/admins/update.html.erb
<h1>Admin::Admins#update</h1>
<p>Find me in app/views/admin/admins/update.html.erb</p>

app/views/admin/admins/withdrawal.html.erb
<h1>Admin::Admins#withdrawal</h1>
<p>Find me in app/views/admin/admins/withdrawal.html.erb</p>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MachiWakka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="logo">
          <%= link_to image_tag('logo.png'), root_path %>
        </div>
        <nav>
          <ul>
            <% if customer_signed_in? %>
            <li class="user-name">ようこそ<%= current_customer.nickname %>さん</li>
            <li><%= link_to  destroy_customer_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"><span class="non-text">&thinsp;ログアウト</span></i>
                <% end %>
            </li>
            <li class="mypage-action">
              <%= link_to top_customers_path do %><i class="fas fa-user"></i>
              <% end %>
            </li>
            <% elsif admin_signed_in? %>
            <li>
              <%= link_to top_admin_shops_path do %>
              <i class="fas fa-store"><span class="non-text">&thinsp;店舗作成</span></i>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"><span class="non-text">&thinsp;ログアウト</span></i>
              <% end %>
            </li>
            <li class="mypage-action"><%= link_to admin_path do %><i class="fas fa-user"></i><% end %></li>
            <% else %>
            <li>
              <%= link_to new_customer_registration_path do %>
              <i class="fas fa-user-plus"><span class="non-text">&thinsp;会員登録</span></i>
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path do %>
              <i class="fas fa-sign-in-alt"><span class="non-text">&thinsp;ログイン</span></i>
              <% end %>
            </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="top-margin"></div>
    <%= link_to "#" ,class: "page-top" do %>
     <i class="fas fa-arrow-up"></i>
    <% end %>
    <%= yield %>
    <footer>
      <div class="footer-menu">
        <div class="footer-menu_logo">
          <% if admin_signed_in? %>
          <%= link_to image_tag('logo-white.png'), admin_path %>
          <% else %>
          <%= link_to image_tag('logo-white.png'), root_path %>
          <% end %>
        </div>
        <ul>
            <% if customer_signed_in? %>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
            <% elsif admin_signed_in? %>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "ユーザーログイン", new_customer_session_path %></li>
            <li><%= link_to "出店者ログイン", new_admin_session_path %></li>
            <% end %>
        </ul>
      </div>
    </footer>
  </body>
</html>